import BoardList from '@components/homepage/boardList/BoardList';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>ABC</h1>

        <Link href="/board">Boards</Link>
        <Link href="/chip">Chips</Link>

        {/* <BoardList /> */}
      </main>
    </div>
  );
}
